alerts:
  dev-check:
    check_url: "/"
    environment: "Production"
    contacts:
      - "stig@silverstripe.com"
      - "sean@silverstripe.com"
  support:
    check_url: "/about-us"
    environment: "UAT"
    contacts:
      - "stig@silverstripe.com"
      - "sean@silverstripe.com"