alerts:
  dev-check:
    envcheck-suite: "pingdom"
    environment: "live-oscar"
    contacts:
      - "stig@silverstripe.com"
      - "sean@silverstripe.com"
  support:
    envcheck-suite: "support"
    environment: "live-oscar"
    contacts:
      - "ops"