alerts:
  dev-check:
    check_url: "/about-us/"
    environment: "Production"
    contacts:
      - "stig@silverstripe.com"
      - "sean@silverstripe.com"
  support:
    check_url: "/"
    environment: "UAT"
    contacts:
      - "stig@silverstripe.com"
      - "sean@silverstripe.com"