infrastructure: 3.5.2
shared_dirs:
  mysite:
    testfolder: {}
apache:
  prefork:
    startservers: "4"
    minspareservers: "3"
    maxspareservers: "7"
    maxclients: "35"
    serverlimit: "35"
    maxrequestsperchild: "20000"
crons:
  mytask:
    time: "0 20 * * *"
    command: "echo \"test cron run 123\" | logger -t SilverStripe_cron"
php_settings:
  http:
    upload_max_filesize: "128M"
    post_max_size: "128M"
  cli:
    memory_limit: "2048M"
alerts:
    prod-check:
      check_url: "/about-us/"
      environment: "Production"
      contacts:
        - "stig@silverstripe.com"
        - "sean@silverstripe.com"
    uat-check:
      check_url: "/"
      environment: "UAT"
      contacts:
        - "stig@silverstripe.com"
        - "sean@silverstripe.com"
